baseURL = "https://wizardwoes.online/"
languageCode = "en-us"
title = "wizardwoes"
sectionPagesMenu = "main"

[taxonomies]
  category = 'categories'
  tag = 'tags'
  cite = 'cite'

[menu]
[[menu.main]]
  identifier = 'glas'
  name = 'glas'
  title = 'glas'
  url = '/glas/'
  weight = 1

[[menu.main]]
  identifier = 'reading-list'
  name = 'reading list'
  title = 'reading list'
  url = '/reading-list/'
  weight = 2

[[menu.main]]
  identifier = 'citations'
  name = 'citations'
  title = 'citations'
  url = '/cite/'
  weight = 3

[[menu.main]]
  identifier = 'photo-weaves'
  name = 'weaves'
  title = 'weaves'
  url = '/photo-weaves/'
  weight = 4

[[menu.main]]
  identifier = 'reagents'
  name = 'reagents'
  title = 'reagents'
  url = '/reagents/'
  weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[module]
[[module.mounts]]
  source = 'content'
  target = 'content'
[[module.mounts]]
  source = 'prebuild/public/jira'
  target = 'content/jira'